-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS as I INNER JOIN ANIMAL_OUTS as O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LEFT(I.SEX_UPON_INTAKE,6)='Intact' AND LEFT(O.SEX_UPON_OUTCOME,6)!='Intact'